"""Server-side persistence layer."""

from lore.persistence.exceptions import (
    BackendUnavailableError,
    ConfigError,
    IntegrityError,
    LoreError,
    ProfileImmutableError,
    StoreBusyError,
    StoreError,
    StoreNotFoundError,
    StoreSchemaMismatchError,
)
from lore.persistence.factory import make_store
from lore.persistence.protocol import Store
from lore.persistence.types import (
    GraphStats,
    MemoryFilter,
    MemoryPatch,
    NewApiKey,
    NewEntity,
    NewMemory,
    NewMember,
    NewMention,
    NewProfile,
    NewRelationship,
    NewWorkspace,
    PendingRelationshipRow,
    ProfilePatch,
    RecallParams,
    ResolvedProfile,
    ScoredMemory,
    StoredApiKey,
    StoredEntity,
    StoredMember,
    StoredMemory,
    StoredMention,
    StoredProfile,
    StoredRelationship,
    StoredWorkspace,
    TimelineBucketRow,
    WorkspacePatch,
)

__all__ = [
    "BackendUnavailableError",
    "ConfigError",
    "GraphStats",
    "IntegrityError",
    "LoreError",
    "MemoryFilter",
    "MemoryPatch",
    "NewApiKey",
    "NewEntity",
    "NewMemory",
    "NewMember",
    "NewMention",
    "NewProfile",
    "NewRelationship",
    "NewWorkspace",
    "PendingRelationshipRow",
    "ProfileImmutableError",
    "ProfilePatch",
    "RecallParams",
    "ResolvedProfile",
    "ScoredMemory",
    "Store",
    "StoreBusyError",
    "StoreError",
    "StoreNotFoundError",
    "StoreSchemaMismatchError",
    "StoredApiKey",
    "StoredEntity",
    "StoredMember",
    "StoredMemory",
    "StoredMention",
    "StoredProfile",
    "StoredRelationship",
    "StoredWorkspace",
    "TimelineBucketRow",
    "WorkspacePatch",
    "make_store",
]
