#!/usr/bin/env bash
# Lore — Full Mac Install (Postgres + pgvector + enrichment pipeline)
# Usage: curl -sSL <url> | bash
#    or: bash install-mac.sh [--api-key YOUR_KEY] [--llm-provider anthropic|openai] [--llm-key sk-...]
set -euo pipefail

# ── Defaults ───────────────────────────────────────────────────────
LORE_PORT=8765
LORE_API_KEY="${LORE_API_KEY:-lore_$(openssl rand -hex 16)}"
LLM_PROVIDER="${LORE_LLM_PROVIDER:-}"
LLM_KEY=""
ENRICHMENT_MODEL="claude-haiku-4"

# ── Parse args ─────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case $1 in
    --api-key)    LORE_API_KEY="$2"; shift 2 ;;
    --llm-provider) LLM_PROVIDER="$2"; shift 2 ;;
    --llm-key)    LLM_KEY="$2"; shift 2 ;;
    --model)      ENRICHMENT_MODEL="$2"; shift 2 ;;
    --port)       LORE_PORT="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

echo "🧠 Lore — Full Mac Install"
echo "=========================="
echo ""

# ── 1. Homebrew ────────────────────────────────────────────────────
if ! command -v brew &>/dev/null; then
  echo "❌ Homebrew not found. Install it first:"
  echo '   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
  exit 1
fi
echo "✅ Homebrew found"

# ── 2. PostgreSQL ──────────────────────────────────────────────────
PG_VERSION=""
for v in 17 16 15; do
  if brew list "postgresql@$v" &>/dev/null; then
    PG_VERSION=$v
    break
  fi
done

if [ -z "$PG_VERSION" ]; then
  echo "📦 Installing PostgreSQL 16..."
  brew install postgresql@16
  PG_VERSION=16
  echo "🔄 Starting PostgreSQL..."
  brew services start "postgresql@$PG_VERSION"
  sleep 2
else
  echo "✅ PostgreSQL $PG_VERSION found"
  # Ensure it's running
  if ! brew services list | grep "postgresql@$PG_VERSION" | grep -q started; then
    echo "🔄 Starting PostgreSQL..."
    brew services start "postgresql@$PG_VERSION"
    sleep 2
  fi
fi

PG_CONFIG="$(brew --prefix "postgresql@$PG_VERSION")/bin/pg_config"
export PATH="$(brew --prefix "postgresql@$PG_VERSION")/bin:$PATH"

# ── 3. pgvector ────────────────────────────────────────────────────
if psql postgres -c "SELECT 1 FROM pg_available_extensions WHERE name='vector'" -t 2>/dev/null | grep -q 1; then
  echo "✅ pgvector already available"
else
  echo "📦 Installing pgvector..."
  # Try Homebrew first
  if brew install pgvector 2>/dev/null; then
    echo "✅ pgvector installed via Homebrew"
  else
    # Build from source
    echo "   Building from source..."
    TMPDIR=$(mktemp -d)
    git clone --branch v0.8.0 --depth 1 https://github.com/pgvector/pgvector.git "$TMPDIR/pgvector"
    cd "$TMPDIR/pgvector"
    make PG_CONFIG="$PG_CONFIG"
    make install PG_CONFIG="$PG_CONFIG"
    cd -
    rm -rf "$TMPDIR"
    echo "✅ pgvector built and installed"
  fi
  # Restart Postgres to pick up the extension
  brew services restart "postgresql@$PG_VERSION"
  sleep 2
fi

# ── 4. Create database ────────────────────────────────────────────
if psql -lqt 2>/dev/null | cut -d \| -f 1 | grep -qw lore; then
  echo "✅ Database 'lore' exists"
else
  echo "📦 Creating database 'lore'..."
  createdb lore
fi

psql lore -c "CREATE EXTENSION IF NOT EXISTS vector;" 2>/dev/null
echo "✅ pgvector extension enabled"

# ── 5. Python + Lore ──────────────────────────────────────────────
if ! command -v python3 &>/dev/null; then
  echo "📦 Installing Python..."
  brew install python@3.12
fi

echo "📦 Installing Lore SDK..."
pip3 install --quiet "lore-sdk[server,enrichment]"
echo "✅ Lore SDK installed ($(pip3 show lore-sdk 2>/dev/null | grep Version | cut -d' ' -f2))"

# ── 6. Environment file ──────────────────────────────────────────
LORE_ENV="$HOME/.lore/env"
mkdir -p "$HOME/.lore"

cat > "$LORE_ENV" <<EOF
# Lore server configuration
# Generated by install-mac.sh on $(date -Iseconds)
LORE_STORE=postgres
LORE_PG_URL=postgresql://localhost/lore
LORE_API_KEY=$LORE_API_KEY
LORE_PORT=$LORE_PORT

# Enrichment pipeline
LORE_ENRICHMENT_ENABLED=true
LORE_CLASSIFY=true
LORE_FACT_EXTRACTION=true
LORE_KNOWLEDGE_GRAPH=true
EOF

# Add LLM config if provided
if [ -n "$LLM_PROVIDER" ]; then
  cat >> "$LORE_ENV" <<EOF

# LLM provider
LORE_LLM_PROVIDER=$LLM_PROVIDER
LORE_ENRICHMENT_MODEL=$ENRICHMENT_MODEL
EOF
  if [ "$LLM_PROVIDER" = "anthropic" ] && [ -n "$LLM_KEY" ]; then
    echo "ANTHROPIC_API_KEY=$LLM_KEY" >> "$LORE_ENV"
  elif [ "$LLM_PROVIDER" = "openai" ] && [ -n "$LLM_KEY" ]; then
    echo "OPENAI_API_KEY=$LLM_KEY" >> "$LORE_ENV"
  fi
fi

echo "✅ Config saved to $LORE_ENV"

# ── 7. LaunchAgent (auto-start on login) ──────────────────────────
PLIST_DIR="$HOME/Library/LaunchAgents"
PLIST_FILE="$PLIST_DIR/com.lore.server.plist"
mkdir -p "$PLIST_DIR"

LORE_BIN=$(command -v lore || echo "$(python3 -c 'import site; print(site.USER_BASE)')/bin/lore")

cat > "$PLIST_FILE" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.lore.server</string>
    <key>ProgramArguments</key>
    <array>
        <string>$LORE_BIN</string>
        <string>serve</string>
        <string>--port</string>
        <string>$LORE_PORT</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
$(while IFS='=' read -r key val; do
    [[ -z "$key" || "$key" == \#* ]] && continue
    echo "        <key>$key</key>"
    echo "        <string>$val</string>"
done < "$LORE_ENV")
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/lore-server.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/lore-server.log</string>
</dict>
</plist>
EOF

# Load (or reload) the service
launchctl unload "$PLIST_FILE" 2>/dev/null || true
launchctl load "$PLIST_FILE"
echo "✅ Lore server started (auto-starts on login)"

# ── 8. Wait for server to be ready ───────────────────────────────
echo -n "⏳ Waiting for server..."
for i in $(seq 1 15); do
  if curl -sf "http://localhost:$LORE_PORT/health" &>/dev/null; then
    echo " ready!"
    break
  fi
  sleep 1
  echo -n "."
done

if ! curl -sf "http://localhost:$LORE_PORT/health" &>/dev/null; then
  echo ""
  echo "⚠️  Server didn't start. Check logs: tail -f /tmp/lore-server.log"
  echo "   You can start manually: source ~/.lore/env && lore serve"
else
  echo "✅ Server healthy at http://localhost:$LORE_PORT"
fi

# ── 9. Setup agent hooks ─────────────────────────────────────────
echo ""
echo "📎 Setting up agent hooks..."

if command -v claude &>/dev/null; then
  lore setup claude-code --server-url "http://localhost:$LORE_PORT" --api-key "$LORE_API_KEY" 2>/dev/null && \
    echo "  ✅ Claude Code hook installed" || echo "  ⚠️  Claude Code setup failed (run manually)"
fi

# Cursor (only if .cursor exists in home or common project dirs)
if [ -d "$HOME/.cursor" ] || [ -d ".cursor" ]; then
  lore setup cursor --server-url "http://localhost:$LORE_PORT" --api-key "$LORE_API_KEY" 2>/dev/null && \
    echo "  ✅ Cursor hook installed" || echo "  ⚠️  Cursor setup failed (run manually)"
fi

echo ""
echo "════════════════════════════════════════"
echo "🧠 Lore is running!"
echo "════════════════════════════════════════"
echo ""
echo "  Server:   http://localhost:$LORE_PORT"
echo "  Health:   http://localhost:$LORE_PORT/health"
echo "  Config:   ~/.lore/env"
echo "  Logs:     /tmp/lore-server.log"
echo "  API Key:  $LORE_API_KEY"
echo ""
echo "Setup more agents:"
echo "  lore setup claude-code --server-url http://localhost:$LORE_PORT --api-key $LORE_API_KEY"
echo "  lore setup cursor     --server-url http://localhost:$LORE_PORT --api-key $LORE_API_KEY"
echo "  lore setup codex      --server-url http://localhost:$LORE_PORT --api-key $LORE_API_KEY"
echo ""
if [ -z "$LLM_PROVIDER" ]; then
  echo "⚠️  No LLM provider configured. Enrichment will skip LLM features."
  echo "   Add to ~/.lore/env:"
  echo "   LORE_LLM_PROVIDER=anthropic"
  echo "   ANTHROPIC_API_KEY=sk-ant-..."
  echo "   Then: launchctl unload ~/Library/LaunchAgents/com.lore.server.plist"
  echo "         launchctl load ~/Library/LaunchAgents/com.lore.server.plist"
  echo ""
fi
echo "Done! 🎉"
